export const ROUTES = {
  home: "/",
  learningCategory: (categoryKey = ":categoryKey") => `/categories/${categoryKey}`,
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  vocabularyTopics: "/vocabulary/topics",
  vocabularyTopicWords: (categoryId = ":categoryId") => `/vocabulary/topics/${categoryId}`,
  vocabularyLevels: "/vocabulary/levels",
  vocabularyMine: "/vocabulary/my",
  listenAndType: "/listening/listen-and-type",
  listenAndTypeLesson: (lessonId = ":lessonId") => `/listening/listen-and-type/${lessonId}`,
  readingIelts: "/reading/ielts",
  readingIeltsSource: (sourceId = ":sourceId") => `/reading/ielts/${sourceId}`,
  writingTask: (taskType = ":taskType") => `/writing/${taskType}`,
  writingProblem: (problemId = ":problemId") => `/writing/practice/${problemId}`,
  dashboard: "/app/dashboard",
  search: "/app/search",
  wordDetail: (wordId = ":wordId") => `/app/words/${wordId}`,
  vocabularies: "/app/vocabularies",
  review: "/app/review",
  listening: "/app/listening",
  listeningDetail: (lessonId = ":lessonId") => `/app/listening/${lessonId}`,
  statistics: "/app/statistics",
  profile: "/app/profile"
} as const;
